### ISSUE TITLE
Qt release mode PDBs are hacky

### ISSUE THREAD

**Issue by rryan** [mixxxdj/buildserver#10]
They are located in src/ and named vc140.pdb. I copy them out but the .libs know their PDB is supposed to be called vc140.pdb. We need to do it the right way with a patch to the Qt makefiles to use ```/PDB:QtCore.pdb``` etc.

https://github.com/mixxxdj/buildserver/blob/msvc15/export_minimal_environment.bat#L67

**Comment by Pegasus-RPG** [comment]
Is this still a problem in Qt5?

**Comment by rryan** [comment]
Nope, this is fixed in Qt5 since they have a proper release-with-debug-info option.

**Comment by rryan** [comment]
Qt 5 fixes this.
