### ISSUE TITLE
Windows: libsndfile clipping on recording broken

### ISSUE THREAD

**Issue by JosepMaJAZ** [mixxxdj/buildserver#30]
This is related to this launchpad bug, that I forgot to verify when we upgraded the buildserver environment:

https://bugs.launchpad.net/mixxx/+bug/1637786

The file build\libsndfile-1.0.26\src\config.h needs to be modified so that the following constant is zero instead of one:

/* Target processor clips on negative float to int conversion. */
#define CPU_CLIPS_NEGATIVE 0

**Comment by rryan** [comment]
Fixed by #31.
