### ISSUE TITLE
Mac/Win: add LAME

### ISSUE THREAD

**Issue by Be-ing** [mixxxdj/buildserver#32]
MP3 patents have finally expired, so we can distribute LAME in binary form for MP3 streaming and recording.

https://bugs.launchpad.net/mixxx/+bug/1294128

**Comment by luzpaz** [comment]
probably should assign this ticket to a milestone version

**Comment by Be-ing** [comment]
As far as I can tell LAME was only added to the macOS build environment but not Windows yet.

**Comment by rryan** [comment]
Windows support was enabled in: https://github.com/mixxxdj/buildserver/commit/9e8bcee771731920ae82f3e076d43f0fb51e5027
and the current build environment for 2.2.x should have it. Are you not seeing it?

**Comment by Be-ing** [comment]
Okay, nevermind then. We should update the manual to remove info about installing LAME then.

**Comment by rryan** [comment]
Yea, LAME still needs to be enabled by default in Mixxx though, and we can remove all the dynamic loading support.
