### ISSUE TITLE
update macOS builder to 10.13

### ISSUE THREAD

**Issue by Be-ing** [mixxxdj/buildserver#57]
The macOS builder is still running macOS 10.11. Eventually this will prevent us from upgrading the macOS SDK to the version required by Qt.

**Comment by Be-ing** [comment]
Shall we target this for 2.3?

**Comment by daschuer** [comment]
I think we can close this one.
It will be pop up again when 10.11 falls out of support from Apple.

**Comment by Be-ing** [comment]
Let's not wait for things to become problems before fixing them.

**Comment by rryan** [comment]
This was easier than I thought it would be. The VM is ready (in Jenkins as build-macosx-10.13-amd64) but I need @Pegasus-RPG to accept the host SSH key from the Jenkins machine.

I will update https://github.com/mixxxdj/buildserver/blob/2.2.x-unix/scripts/macosx/SETUP.md with the latest instructions for settting up a macOS builder.

**Comment by Be-ing** [comment]
@rryan remember to update the Jenkins configuration scripts to point to the new version of the macOS SDK (#59).

**Comment by rryan** [comment]
I already updated the Jenkins config to detect the installed SDK instead of hard-coding a version. :)

**Comment by rryan** [comment]
I also have a PR that I'll open once the new VM is enabled that updates `build_environment.sh` to auto-detect the SDK by default.
